### ISSUE TITLE
count_total

### ISSUE THREAD

**Issue by nikdenly** [darkfriend/hlhelpers#1]
Не работает count_total @param array $arMoreParams остальные параметры select|group|limit|offset|count_total|runtime|data_doubling в гетлистах.

Для получения количества используется еще один запрос.
Так что для обработки результата
`while ($arData = $rsData->Fetch()) {
            $arResult[] = $rsData->getCount();
}`
нужен дозапрос $rsData->getCount();
либо отдельный метод

**Comment by darkfriend** [comment]
Здравствуйте.
Спасибо за обращение и ожидание.

В версии 1.0.3 добавлен метод `getTotalCount`, это решит вашу задачу.
